[tool.poetry]
name = "auth-service"
version = "0.1.0"
description = "Auth microservice"
authors = ["saveliyu <uljanoff.sav@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
fastapi = "^0.141.1"
sqlalchemy = "^2.0.52"
alembic = "^1.19.1"
uvicorn = "^0.52.4"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
pytest-asyncio = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


